name: Test and Log Metrics

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tests and collect metrics
      run: |
        python -m pytest tests/ --junitxml=test-results.xml
        
    - name: Upload metrics
      uses: actions/upload-artifact@v2
      with:
        name: metrics-logs
        path: logs/

    - name: Update README with latest metrics
      run: |
        python scripts/update_readme_metrics.py 